config/routes.rb
MissionControl::Jobs::Engine.routes.draw do
  resources :applications, only: [] do
    resources :queues, only: [ :index, :show ] do
      scope module: :queues do
        resource :pause, only: [ :create, :destroy ]
      end
    end

    resources :jobs, only: :show do
      resource :retry, only: :create
      resource :discard, only: :create
      resource :dispatch, only: :create

      collection do
        resource :bulk_retries, only: :create
        resource :bulk_discards, only: :create
      end
    end

    resources :jobs, only: :index, path: ":status/jobs"

    resources :workers, only: [ :index, :show ]
    resources :recurring_tasks, only: [ :index, :show, :update ]
  end

  # Allow referencing urls without providing an application_id. It will default to the first one.
  resources :queues, only: [ :index, :show ]

  resources :jobs, only: :show
  resources :jobs, only: :index, path: ":status/jobs"

  root to: "queues#index"
end

app/models/mission_control/jobs/application_record.rb
module MissionControl
  module Jobs
    class ApplicationRecord < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end

app/models/mission_control/jobs/current.rb
class MissionControl::Jobs::Current < ActiveSupport::CurrentAttributes
  attribute :application, :server
end

app/models/mission_control/jobs/page.rb
class MissionControl::Jobs::Page
  DEFAULT_PAGE_SIZE = 10

  attr_reader :records, :index, :page_size

  def initialize(relation, page: 1, page_size: DEFAULT_PAGE_SIZE)
    @relation = relation
    @page_size = page_size
    @index = [ page, 1 ].max
  end

  def records
    @relation.limit(page_size).offset(offset)
  end

  def first?
    index == 1
  end

  def last?
    index == pages_count || empty? || records.empty?
  end

  def empty?
    total_count == 0
  end

  def previous_index
    [ index - 1, 1 ].max
  end

  def next_index
    pages_count ? [ index + 1, pages_count ].min : index + 1
  end

  def pages_count
    (total_count.to_f / page_size).ceil unless total_count.infinite?
  end

  def total_count
    @total_count ||= @relation.count # Potentially expensive when filtering a lot of records, with the adapter in charge of doing the filtering in memory
  end

  private
    def offset
      (index - 1) * page_size
    end
end

app/models/mission_control/jobs/recurring_task.rb
class MissionControl::Jobs::RecurringTask
  include ActiveModel::Model

  attr_accessor :id, :job_class_name, :command, :arguments, :schedule, :last_enqueued_at, :next_time, :queue_name, :priority

  def initialize(queue_adapter: ActiveJob::Base.queue_adapter, **kwargs)
    @queue_adapter = queue_adapter
    super(**kwargs)
  end

  def jobs
    ActiveJob::JobsRelation.new(queue_adapter: queue_adapter).where(recurring_task_id: id)
  end

  def enqueue
    queue_adapter.enqueue_recurring_task(id)
  end

  def runnable?
    queue_adapter.can_enqueue_recurring_task?(id)
  end

  private
    attr_reader :queue_adapter
end

app/models/mission_control/jobs/worker.rb
class MissionControl::Jobs::Worker
  include ActiveModel::Model

  attr_accessor :id, :name, :hostname, :last_heartbeat_at, :configuration, :raw_data

  def initialize(queue_adapter: ActiveJob::Base.queue_adapter, **kwargs)
    @queue_adapter = queue_adapter
    super(**kwargs)
  end

  def jobs
    @jobs ||= ActiveJob::JobsRelation.new(queue_adapter: queue_adapter).in_progress.where(worker_id: id)
  end

  private
    attr_reader :queue_adapter
end

app/models/mission_control/jobs/workers_page.rb
class MissionControl::Jobs::WorkersPage
  DEFAULT_PAGE_SIZE = 10

  attr_reader :workers_collection, :index, :page_size

  def initialize(workers_collection, page: 1, page_size: DEFAULT_PAGE_SIZE)
    @workers_collection = workers_collection
    @page_size = page_size
    @index = [ page, 1 ].max
  end

  def workers
    workers_collection.drop(offset).first(page_size)
  end

  def first?
    index == 1
  end

  def last?
    index == pages_count || empty? || workers.empty?
  end

  def empty?
    total_count == 0
  end

  def previous_index
    [ index - 1, 1 ].max
  end

  def next_index
    pages_count ? [ index + 1, pages_count ].min : index + 1
  end

  def pages_count
    (total_count.to_f / 10).ceil unless total_count.infinite?
  end

  def total_count
    @total_count ||= workers_collection.count # Potentially expensive when filtering and a lot of workers, with adapter in charge of doing the filtering in memory
  end

  private
    def offset
      (index - 1) * page_size
    end
end

app/controllers/concerns/mission_control/jobs/adapter_features.rb
module MissionControl::Jobs::AdapterFeatures
  extend ActiveSupport::Concern

  included do
    helper_method :supported_job_statuses, :queue_pausing_supported?, :workers_exposed?, :supports_dashboard?, :recurring_tasks_supported?
  end

  private
    def supported_job_statuses
      MissionControl::Jobs::Current.server.queue_adapter.supported_job_statuses & ActiveJob::JobsRelation::STATUSES
    end

    def queue_pausing_supported?
      MissionControl::Jobs::Current.server.queue_adapter.supports_queue_pausing?
    end

    def workers_exposed?
      MissionControl::Jobs::Current.server.queue_adapter.exposes_workers?
    end

    def recurring_tasks_supported?
      MissionControl::Jobs::Current.server.queue_adapter.supports_recurring_tasks?
    end

    def supports_dashboard?
      MissionControl::Jobs::Current.server.queue_adapter.supports_dashboard?
    end
end

app/controllers/concerns/mission_control/jobs/application_scoped.rb
module MissionControl::Jobs::ApplicationScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_application
    around_action :activating_job_server

    delegate :applications, to: MissionControl::Jobs
  end

  private
    def set_application
      @application = find_application or raise MissionControl::Jobs::Errors::ResourceNotFound, "Application not found"
      MissionControl::Jobs::Current.application = @application
    end

    def find_application
      if params[:application_id]
        applications[params[:application_id]]
      else
        applications.first
      end
    end

    def activating_job_server(&block)
      @server = find_server or raise MissionControl::Jobs::Errors::ResourceNotFound, "Server not found"
      MissionControl::Jobs::Current.server = @server
      @server.activating(&block)
    end

    def find_server
      if params[:server_id]
        MissionControl::Jobs::Current.application.servers[params[:server_id]]
      else
        @application.servers.first
      end
    end
end

app/controllers/concerns/mission_control/jobs/basic_authentication.rb
module MissionControl::Jobs::BasicAuthentication
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_by_http_basic
  end

  private
    def authenticate_by_http_basic
      if http_basic_authentication_enabled?
        if http_basic_authentication_configured?
          http_basic_authenticate_or_request_with(**http_basic_authentication_credentials)
        else
          head :unauthorized
        end
      end
    end

    def http_basic_authentication_enabled?
      MissionControl::Jobs.http_basic_auth_enabled
    end

    def http_basic_authentication_configured?
      http_basic_authentication_credentials.values.all?(&:present?)
    end

    def http_basic_authentication_credentials
      {
        name: MissionControl::Jobs.http_basic_auth_user,
        password: MissionControl::Jobs.http_basic_auth_password
      }.transform_values(&:presence)
    end
end

app/controllers/concerns/mission_control/jobs/failed_jobs_bulk_operations.rb
module MissionControl::Jobs::FailedJobsBulkOperations
  extend ActiveSupport::Concern

  MAX_NUMBER_OF_JOBS_FOR_BULK_OPERATIONS = 3000

  included do
    include MissionControl::Jobs::JobFilters
  end

  private
    # We set a hard limit to prevent problems with the data store (for example, overloading Redis
    # or causing replication lag in MySQL). This should be enough for most scenarios. For
    # cases where we need to retry a huge sets of jobs, we offer a runbook that uses the API.
    def bulk_limited_filtered_failed_jobs
      ActiveJob.jobs.failed.where(**@job_filters).limit(MAX_NUMBER_OF_JOBS_FOR_BULK_OPERATIONS)
    end
end

app/controllers/concerns/mission_control/jobs/job_filters.rb
module MissionControl::Jobs::JobFilters
  extend ActiveSupport::Concern

  included do
    before_action :set_filters

    helper_method :active_filters?, :jobs_filter_param
  end

  private
    def set_filters
      @job_filters = {
        job_class_name: params.dig(:filter, :job_class_name).presence,
        queue_name: params.dig(:filter, :queue_name).presence,
        finished_at: finished_at_range_params
      }.compact
    end

    def active_filters?
      @job_filters.any?
    end

    def jobs_filter_param
      if @job_filters&.any?
        { filter: @job_filters }
      else
        {}
      end
    end

    def finished_at_range_params
      range_start, range_end = params.dig(:filter, :finished_at_start), params.dig(:filter, :finished_at_end)
      if range_start || range_end
        (parse_with_time_zone(range_start)..parse_with_time_zone(range_end))
      end
    end

    def parse_with_time_zone(date)
      Time.zone.parse(date) if date.present?
    end
end

app/controllers/concerns/mission_control/jobs/job_scoped.rb
module MissionControl::Jobs::JobScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_job
  end

  private
    def set_job
      @job = jobs_relation.find_by_id!(params[:job_id] || params[:id])
    end

    def jobs_relation
      raise NotImplementedError
    end
end

app/controllers/concerns/mission_control/jobs/not_found_redirections.rb
module MissionControl::Jobs::NotFoundRedirections
  extend ActiveSupport::Concern

  included do
    rescue_from(ActiveJob::Errors::JobNotFoundError) do |error|
      redirect_to best_location_for_job_relation(error.job_relation), alert: error.message
    end

    rescue_from(MissionControl::Jobs::Errors::ResourceNotFound) do |error|
      redirect_to best_location_for_resource_not_found_error(error), alert: error.message
    end
  end

  private
    def best_location_for_job_relation(job_relation)
      case
      when job_relation.failed?
        application_jobs_path(@application, :failed)
      when job_relation.queue_name.present?
        application_queue_path(@application, job_relation.queue_name)
      else
        root_path
      end
    end

    def best_location_for_resource_not_found_error(error)
      if error.message.match?(/recurring task/i)
        application_recurring_tasks_path(@application)
      else
        root_url
      end
    end
end

app/controllers/concerns/mission_control/jobs/queue_scoped.rb
module MissionControl::Jobs::QueueScoped
  extend ActiveSupport::Concern

  included do
    before_action :set_queue
  end

  private
    def set_queue
      @queue = ActiveJob.queues[params[:queue_id]] or raise MissionControl::Jobs::Errors::ResourceNotFound, "Queue '#{params[:queue_id]}' not found"
    end
end

app/controllers/mission_control/jobs/application_controller.rb
class MissionControl::Jobs::ApplicationController < MissionControl::Jobs.base_controller_class.constantize
  ActionController::Base::MODULES.each do |mod|
    include mod unless self < mod
  end

  layout "mission_control/jobs/application"

  # Include helpers if not already included
  helper MissionControl::Jobs::ApplicationHelper unless self < MissionControl::Jobs::ApplicationHelper
  helper Importmap::ImportmapTagsHelper unless self < Importmap::ImportmapTagsHelper

  include MissionControl::Jobs::BasicAuthentication
  include MissionControl::Jobs::ApplicationScoped, MissionControl::Jobs::NotFoundRedirections
  include MissionControl::Jobs::AdapterFeatures
  include MissionControl::Jobs::JobFilters

  around_action :set_current_locale

  private
    def default_url_options
      { server_id: MissionControl::Jobs::Current.server }
    end

    def set_current_locale(&block)
      @previous_config = I18n.config
      I18n.config = MissionControl::Jobs::I18nConfig.new
      I18n.with_locale(:en, &block)
    ensure
      I18n.config = @previous_config
      @previous_config = nil
    end
end

app/controllers/mission_control/jobs/bulk_discards_controller.rb
class MissionControl::Jobs::BulkDiscardsController < MissionControl::Jobs::ApplicationController
  include MissionControl::Jobs::FailedJobsBulkOperations

  def create
    jobs_to_discard_count = jobs_to_discard.count
    jobs_to_discard.discard_all

    redirect_to application_jobs_url(@application, :failed), notice: "Discarded #{jobs_to_discard_count} jobs"
  end

  private
    def jobs_to_discard
      if active_filters?
        bulk_limited_filtered_failed_jobs
      else
        # we don't want to apply any limit since "discarding all" without parameters can be optimized in the adapter as a much faster operation
        ActiveJob.jobs.failed
      end
    end
end

app/controllers/mission_control/jobs/bulk_retries_controller.rb
class MissionControl::Jobs::BulkRetriesController < MissionControl::Jobs::ApplicationController
  include MissionControl::Jobs::FailedJobsBulkOperations

  def create
    jobs_to_retry_count = bulk_limited_filtered_failed_jobs.count
    bulk_limited_filtered_failed_jobs.retry_all

    redirect_to application_jobs_url(@application, :failed), notice: "Retried #{jobs_to_retry_count} jobs"
  end
end

app/controllers/mission_control/jobs/dashboard_controller.rb
class MissionControl::Jobs::DashboardController < MissionControl::Jobs::ApplicationController
  def index
  end
end

app/controllers/mission_control/jobs/discards_controller.rb
class MissionControl::Jobs::DiscardsController < MissionControl::Jobs::ApplicationController
  include MissionControl::Jobs::JobScoped

  def create
    @job.discard
    redirect_to redirect_location, notice: "Discarded job with id #{@job.job_id}"
  end

  private
    def jobs_relation
      ActiveJob.jobs
    end

    def redirect_location
      status = @job.status.presence_in(supported_job_statuses) || :failed
      application_jobs_url(@application, status, **jobs_filter_param)
    end
end

app/controllers/mission_control/jobs/dispatches_controller.rb
class MissionControl::Jobs::DispatchesController < MissionControl::Jobs::ApplicationController
  include MissionControl::Jobs::JobScoped

  def create
    @job.dispatch
    redirect_to redirect_location, notice: "Dispatched job with id #{@job.job_id}"
  end

  private
    def jobs_relation
      ActiveJob.jobs
    end

    def redirect_location
      status = @job.status.presence_in(supported_job_statuses) || :blocked
      application_jobs_url(@application, status)
    end
end

app/views/mission_control/jobs/recurring_tasks/_actions.html.erb
<div class="buttons is-right">
  <% if recurring_task.runnable? %>
    <%= button_to "Run now", application_recurring_task_path(@application, recurring_task.id), class: "button is-warning is-light mr-0", method: :put %>
  <% end %>
</div>

app/views/mission_control/jobs/recurring_tasks/_general_information.html.erb
<table class="table">
  <tbody>
  <% if recurring_task.job_class_name.present? %>
    <tr>
      <th>Job class</th>
      <td><%= recurring_task.job_class_name %></td>
    </tr>

    <tr>
      <th>Arguments</th>
      <td><div class="is-family-monospace"><%= recurring_task.arguments.join(",") %></div></td>
    </tr>
  <% elsif recurring_task.command.present? %>
    <tr>
      <th>Command</th>
      <td><div class="is-family-monospace"><%= recurring_task.command %></div></td>
    </tr>
  <% end %>

  <tr>
    <th>Schedule</th>
    <td><%= recurring_task.schedule %></td>
  </tr>
  <% if recurring_task.queue_name.present? %>
    <tr>
      <th>Queue</th>
      <td><%= recurring_task.queue_name %></td>
    </tr>
  <% end %>
  <% if recurring_task.priority.present? %>
    <tr>
      <th>Priority</th>
      <td><%= recurring_task.priority %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/mission_control/jobs/recurring_tasks/_recurring_task.html.erb
<tr class="recurring_task">
  <td>
    <%= link_to recurring_task.id, application_recurring_task_path(@application, recurring_task.id) %>
  </td>
  <td>
    <% if recurring_task.job_class_name.present? %>
      <%= recurring_task.job_class_name %>

      <% if recurring_task.arguments.present? %>
        <div class="is-family-monospace"><%= recurring_task.arguments.join(",") %></div>
      <% end %>
    <% elsif recurring_task.command.present? %>
      <div class="is-family-monospace"><%= recurring_task.command %></div>
    <% end %>
  </td>
  <td> <%= recurring_task.schedule %> </td>
  <td><div class="has-text-grey"><%= recurring_task.last_enqueued_at ? bidirectional_time_distance_in_words_with_title(recurring_task.last_enqueued_at) : "Never" %></div></td>
  <td class="next_time"><div class="has-text-grey"><%= bidirectional_time_distance_in_words_with_title(recurring_task.next_time) %></div></td>
  <td class="pr-0">
    <%= render "mission_control/jobs/recurring_tasks/actions", recurring_task: recurring_task %>
  </td>
</tr>

app/views/mission_control/jobs/recurring_tasks/_title.html.erb
<h1 class="title">
  <div class="level">
    <div class="level-left">
      <%= recurring_task.id %>
    </div>
    <div class="level-right">
      <%= render "mission_control/jobs/recurring_tasks/actions", recurring_task: recurring_task %>
    </div>
  </div>
</h1>

app/views/mission_control/jobs/recurring_tasks/index.html.erb
<% navigation(title: "Recurring tasks", section: :recurring_tasks)  %>

<table class="recurring-tasks table jobs is-hoverable is-fullwidth">
  <tbody>
  <thead>
  <tr>
    <th></th>
    <th>Job</th>
    <th>Schedule</th>
    <th>Last enqueued</th>
    <th>Next</th>
    <th></th>
  </tr>
  </thead>

  <%= render partial: "mission_control/jobs/recurring_tasks/recurring_task", collection: @recurring_tasks %>
  </tbody>
</table>

app/views/mission_control/jobs/recurring_tasks/show.html.erb
<% navigation(title: @recurring_task.id, section: :recurring_tasks) %>

<%= render "mission_control/jobs/recurring_tasks/title", recurring_task: @recurring_task %>
<%= render "mission_control/jobs/recurring_tasks/general_information", recurring_task: @recurring_task %>

<% if @jobs_page.empty? %>
  <%= blank_status_notice "No jobs found for this recurring task" %>
<% else %>
  <h2 class="subtitle"><%= pluralize @recurring_task.jobs.count, "job" %></h2>

  <%= render "mission_control/jobs/shared/jobs", jobs: @jobs_page.records %>

  <%= render "mission_control/jobs/shared/pagination_toolbar", page: @jobs_page, filter_param: jobs_filter_param %>
<% end %>